language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: LanguageModelFeaturizer
    model_name: distilbert
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy